kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: artifactregistry-admin
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    rbac.authorization.k8s.io/aggregate-to-cluster-reader: "true"
rules:
  - verbs:
      - get
      - watch
      - list
      - create
      - update
      - patch
      - delete
    apiGroups:
      - artifactregistry.arthurvardevanyan.com
    resources:
      - auths
      - auths/status
