# permissions for end users to edit auths.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: auth-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: artifact-registry-k8s-auth-controller
    app.kubernetes.io/part-of: artifact-registry-k8s-auth-controller
    app.kubernetes.io/managed-by: kustomize
  name: auth-editor-role
rules:
- apiGroups:
  - artifact-registry.arthurvardevanyan.com
  resources:
  - auths
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - artifact-registry.arthurvardevanyan.com
  resources:
  - auths/status
  verbs:
  - get
