---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-manager-role
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
      - delete
      - update
  - apiGroups:
      - ""
    resources:
      - serviceaccounts
    verbs:
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - serviceaccounts/token
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: clusterrolebinding
    app.kubernetes.io/instance: cluster-manager-rolebinding
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: artifact-registry-k8s-auth-controller
    app.kubernetes.io/part-of: artifact-registry-k8s-auth-controller
    app.kubernetes.io/managed-by: kustomize
  name: cluster-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-manager-role
subjects:
  - kind: ServiceAccount
    name: controller-manager
    namespace: system
