---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
      - delete
      - update
  - apiGroups:
      - ""
    resources:
      - serviceaccounts
    verbs:
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - serviceaccounts/token
    verbs:
      - create
  - apiGroups:
      - artifactregistry.arthurvardevanyan.com
    resources:
      - auths
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - artifactregistry.arthurvardevanyan.com
    resources:
      - auths/finalizers
    verbs:
      - update
  - apiGroups:
      - artifactregistry.arthurvardevanyan.com
    resources:
      - auths/status
    verbs:
      - get
      - patch
      - update
