apiVersion: artifactregistry.arthurvardevanyan.com/v1beta1
kind: Auth
metadata:
  name: example
  namespace: smoke-tests
spec:
  registryLocation: us-central1
  secretName: artifact-registry-auth
  wifConfig:
    fileName: credentials_config.json
    objectName: google-wif-config
    serviceAccount: wif-test
    type: configMap
